### ISSUE TITLE
Remove ac detection

### ISSUE THREAD

**Issue by jobitjoseph** [ManojBR105/ARDUINO-SMD-REWORK-STATION#1]
Hi thanks for the code. I would like to use a triac driver with internal zero cross detection like MOC3041/MOC3063 so we can avoid the zero cross detection circuit completely. So what changes should do to the code. Thanks in advance

**Comment by ManojBR105** [comment]
> Hi thanks for the code. I would like to use a triac driver with internal zero cross detection like MOC3041/MOC3063 so we can avoid the zero cross detection circuit completely. So what changes should do to the code. Thanks in advance

It's not as simple as it sounds. Because zero Cross detector is not only used to drive triac but also an integral part of calculating power. It helps the Arduino to count AC wave cycles. So I don't think it is good idea to eliminate the ZCD.

**Comment by AHVEJDANI** [comment]
Hi
Tanks for coding
Why can't the CommonControls library be installed?
Please help me.

**Comment by ManojBR105** [comment]
Can you please EXPLAIN!! what do you mean by not able to install.
Are you not able to include it or is Arduino ide throughing some errors.

**Comment by AHVEJDANI** [comment]
Thanks for your response
I get an error while compiling the program with arduino ide
This error :  no matching function for call to ‘DSPL::begin()’
How do I fix it??

**Comment by AHVEJDANI** [comment]
Thanks for your response
I get an error while compiling the program with arduino ide
This error :  no matching function for call to ‘DSPL::begin()’
How do I fix it??

A.H Vejdani

**Comment by ManojBR105** [comment]
> 
> Thanks for your response
> I get an error while compiling the program with arduino ide
> This error :  no matching function for call to ‘DSPL::begin()’
> How do I fix it??
> 
> A.H Vejdani
> 
> > On Sep 10, 2020, at 11:36, Maker BR <notifications@github.com> wrote:
> > 
> > ﻿
> > Can you please EXPLAIN!! what do you mean by not able to install.
> > Are you not able to include it or is Arduino ide throughing some errors.
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
 try replacing DSPL::init() with DSPL::begin()
See if the error still exists

**Comment by AHVEJDANI** [comment]
It's working 
Thank you so much 
😘
